// Codegen for the Tauri 2 plugin permission system.
//
// `tauri-plugin::Builder` reads `permissions/` and emits the
// per-command default-permission manifest the host app references in
// its capability files. We declare every command we want JS to be
// able to invoke here so it shows up in the autogenerated set.
const COMMANDS: &[&str] = &[
    "is_supported",
    "attach",
    "detach",
    "is_attached",
    "create_panel",
    "close_panel",
    "set_panel_bounds",
    "set_panel_interactive",
    "set_panel_z_index",
    "post_panel_message",
    "ping_shell",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
